In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D,  BatchNormalization, MaxPooling2D, Flatten
from tensorflow.keras.datasets import cifar10
from keras.utils import np_utils

In [2]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 6d958be074577803d12ecdefd02955f39262c83c16fe9348329d7fe0b5c001ce so we will re-download the data.
170498071/170498071 [==============================] - 200s 1us/step


In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
y_train.shape

(50000, 1)

In [5]:
x_train = x_train/255
x_test = x_test/255

In [6]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [7]:

y_train = np_utils.to_categorical(y_train,10)
y_test = np_utils.to_categorical(y_test,10)

In [8]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
model = Sequential()
model.add(Conv2D(32, (3,3), activation= 'relu', input_shape = (32,32,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Conv2D(64, (3,3), activation= 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.3))
model.add(Conv2D(128, (3,3), activation= 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dense(128, activation= 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(10, activation= "softmax"))

Metal device set to: Apple M1


2022-12-19 11:44:44.308822: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-19 11:44:44.308954: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 32)        896       
                                                                 
 batch_normalization (BatchN  (None, 30, 30, 32)       128       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 15, 15, 32)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 batch_normalization_1 (Batc  (None, 13, 13, 64)       2

In [11]:
model.compile(loss = 'categorical_crossentropy', optimizer= 'adam', metrics= ['accuracy'])

In [12]:
model.fit(x_train, y_train, batch_size=64, epochs=10 , validation_data= (x_test, y_test))

Epoch 1/10


2022-12-19 11:44:45.813548: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-12-19 11:44:46.231046: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


782/782 [==============================] - ETA: 0s - loss: 1.7706 - accuracy: 0.3936

2022-12-19 11:45:05.964718: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


782/782 [==============================] - 21s 22ms/step - loss: 1.7706 - accuracy: 0.3936 - val_loss: 1.4553 - val_accuracy: 0.4679
Epoch 2/10
782/782 [==============================] - 16s 20ms/step - loss: 1.3189 - accuracy: 0.5288 - val_loss: 1.2890 - val_accuracy: 0.5363
Epoch 3/10
782/782 [==============================] - 16s 20ms/step - loss: 1.1762 - accuracy: 0.5847 - val_loss: 1.1104 - val_accuracy: 0.6020
Epoch 4/10
782/782 [==============================] - 16s 21ms/step - loss: 1.0783 - accuracy: 0.6210 - val_loss: 1.1458 - val_accuracy: 0.5948
Epoch 5/10
782/782 [==============================] - 16s 21ms/step - loss: 1.0100 - accuracy: 0.6457 - val_loss: 1.4048 - val_accuracy: 0.5493
Epoch 6/10
782/782 [==============================] - 16s 21ms/step - loss: 0.9605 - accuracy: 0.6646 - val_loss: 1.1651 - val_accuracy: 0.6073
Epoch 7/10
782/782 [==============================] - 16s 21ms/step - loss: 0.9240 - accuracy: 0.6752 - val_loss: 0.8895 - val_accuracy: 0.6935
Epo

In [13]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 2s 8ms/step - loss: 0.9264 - accuracy: 0.6772


[0.9264078736305237, 0.6772000193595886]

In [14]:
np.argmax(model.predict(x_test) , axis = -1)

 43/313 [===>..........................] - ETA: 0s

2022-12-19 11:47:35.396542: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


313/313 [==============================] - 1s 4ms/step


array([3, 0, 0, ..., 5, 0, 7])